app/api/__init__.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
"""API functions."""
from flask import render_template
from flask import request
from flask import jsonify
from flask import Blueprint

api = Blueprint("api", __name__)


@api.route("/")
def homepage():
    return jsonify({"status": "on", "api_version": "1.0"})


@api.route("/add_data", methods=["POST"])
def add_data():
    """Add data via an API endpoint to the database.

    Required: doi
    Optional: url, date
    """
    response_status = "error"
    url_type_list = [
        "ojs",
        "doi_new",
        "doi_old",
        "doi_new_landingpage",
        "unpaywall",
        "pubmed",
        "pubmedcentral",
    ]

    json_data = request.get_json()
    token = json_data["token"]

    if request.method == "POST":
        try:
            if "X-API-Key" in request.headers:
                if app.config["API_TOKEN"] == request.headers["X-API-Key"]:
                    if request.headers["Content-Type"] == "application/json":
                        json_data = request.get_json()
                        if isinstance(json_data, list):
                            is_data_valid = True
                            for entry in data:
                                # Validate entry
                                if "doi" in entry:
                                    if not isinstance(entry["doi"], str):
                                        response = "DOI {} is no string.".format(
                                            entry["doi"]
                                        )
                                        is_data_valid = False
                                    if "url" in entry:
                                        if not isinstance(entry["url"], str):
                                            response = "URL {} is no string.".format(
                                                entry["url"]
                                            )
                                            is_data_valid = False
                                    else:
                                        print("URL is missing")
                                        is_data_valid = False
                                    if "url_type" in entry:
                                        if not isinstance(entry["url_type"], str):
                                            response = "URL type {} is no string.".format(
                                                entry["url_type"]
                                            )
                                            is_data_valid = False
                                        if entry["url_type"] not in url_type_list:
                                            response = "URL type {} is not one of the allowed types.".format(
                                                entry["url_type"]
                                            )
                                            is_data_valid = False
                                        else:
                                            response = "URL type is missing."
                                            is_data_valid = False
                                    if "date" in entry:
                                        if not isinstance(entry["date"], str):
                                            response = "Date {} is no string.".format(
                                                entry["date"]
                                            )
                                            is_data_valid = False
                                    else:
                                        response = "Date is missing."
                                        is_data_valid = False
                                else:
                                    is_data_valid = False
                                    response = "DOI is missing in {}.".format(entry)
                            if is_data_valid:
                                resp_func = import_dois_from_api(data)
                                if resp_func:
                                    response = resp_func
                                    response_status = "ok"
                                else:
                                    response = "Error: JSON from API could not be stored in database."
                        else:
                            response = "No list of data in JSON."
                    else:
                        response = "No JSON delivered."
                else:
                    response = "Authentication token not right."
            else:
                response = "Authentication token not passed."
        except:
            response = "Undefined error."

        return jsonify({"status": response_status, "content": response})

app/bp/api/__init__.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
"""API functions."""
from flask import Blueprint
from flask import jsonify


blueprint = Blueprint("api", __name__)


@blueprint.route("/")
def index() -> str:
    """Get API root."""
    return jsonify(
        [
            {
                "path": "/v1",
                "name": "v1",
                "version": "1.0.0",
                "major": 1,
                "minor": 0,
                "micro": 0,
                "release_date": "2020-11-16",
                "status": "online",
            }
        ]
    )

app/bp/api/v1/__init__.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
"""API functions."""
from flask import Blueprint
from flask import current_app
from flask import jsonify
from flask import request


blueprint = Blueprint("v1", __name__)


@blueprint.route("/")
def index() -> dict:
    """Return index."""
    return {"path": "add_data/", "name": "add_data"}


@blueprint.route("/add_data", methods=["POST"])
def add_data() -> str:
    """Add data via an API endpoint to the database.

    Required: doi
    Optional: url, date
    """
    # TODO: merge with index or remove /add_data url from blueprint
    response_status = "error"
    url_type_list = [
        "ojs",
        "doi_new",
        "doi_old",
        "doi_new_landingpage",
        "unpaywall",
        "pubmed",
        "pubmedcentral",
    ]

    json_data = request.get_json()
    # token = json_data["token"]

    if request.method == "POST":
        try:
            if "X-API-Key" in request.headers:
                if current_app.config["API_TOKEN"] == request.headers["X-API-Key"]:
                    if request.headers["Content-Type"] == "application/json":
                        json_data = request.get_json()
                        if isinstance(json_data, list):
                            is_data_valid = True
                            for entry in json_data:
                                # Validate entry
                                if "doi" in entry:
                                    if not isinstance(entry["doi"], str):
                                        response = "DOI {} is no string.".format(
                                            entry["doi"]
                                        )
                                        is_data_valid = False
                                    if "url" in entry:
                                        if not isinstance(entry["url"], str):
                                            response = "URL {} is no string.".format(
                                                entry["url"]
                                            )
                                            is_data_valid = False
                                    else:
                                        print("URL is missing")
                                        is_data_valid = False
                                    if "url_type" in entry:
                                        if not isinstance(entry["url_type"], str):
                                            response = "URL type {} is no string.".format(
                                                entry["url_type"]
                                            )
                                            is_data_valid = False
                                        if entry["url_type"] not in url_type_list:
                                            response = "URL type {} is not one of the allowed types.".format(
                                                entry["url_type"]
                                            )
                                            is_data_valid = False
                                        else:
                                            response = "URL type is missing."
                                            is_data_valid = False
                                    if "date" in entry:
                                        if not isinstance(entry["date"], str):
                                            response = "Date {} is no string.".format(
                                                entry["date"]
                                            )
                                            is_data_valid = False
                                    else:
                                        response = "Date is missing."
                                        is_data_valid = False
                                else:
                                    is_data_valid = False
                                    response = "DOI is missing in {}.".format(entry)
                            if is_data_valid:
                                # TODO: import_dois_from_api
                                resp_func = import_dois_from_api(data)
                                if resp_func:
                                    response = resp_func
                                    response_status = "ok"
                                else:
                                    response = "Error: JSON from API could not be stored in database."
                        else:
                            response = "No list of data in JSON."
                    else:
                        response = "No JSON delivered."
                else:
                    response = "Authentication token not right."
            else:
                response = "Authentication token not passed."
        except:
            raise ("Undefined error.")

        return jsonify({"status": response_status, "content": response})

app/bp/main/__init__.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
"""main functions."""
from flask import Blueprint
from flask import current_app
from flask import render_template
from flask_sqlalchemy import get_debug_queries
from requests import Response

from app.db import get_db
from app.models import Doi
from app.models import FBRequest
from app.models import Import
from app.models import Request
from app.models import Url


blueprint = Blueprint("main", __name__)


@blueprint.route("/")
@blueprint.route("/index")
def index() -> str:
    """Homepage."""
    return render_template("index.html", title="Home")


@blueprint.route("/stats")
def stats() -> str:
    """Statistics."""
    db = get_db()
    data = {
        "imports": db.session.query(Import).count(),
        "dois": {
            "num": db.session.query(Doi).count(),
            "new": db.session.query(Doi).filter(Doi.url_doi_new == True).count(),
            "old": db.session.query(Doi).filter(Doi.url_doi_old == True).count(),
            "lp": db.session.query(Doi).filter(Doi.url_doi_lp == True).count(),
            "ncbi": db.session.query(Doi).filter(Doi.url_ncbi == True).count(),
            "pmc": db.session.query(Doi).filter(Doi.url_pmc == True).count(),
            "pm": db.session.query(Doi).filter(Doi.url_pm == True).count(),
            "unpaywall": db.session.query(Doi)
            .filter(Doi.url_unpaywall == True)
            .count(),
        },
        "urls": {
            "num": db.session.query(Url).count(),
            "new": db.session.query(Url).filter(Url.url_type == "doi_new").count(),
            "old": db.session.query(Url).filter(Url.url_type == "doi_old").count(),
            "lp": db.session.query(Url).filter(Url.url_type == "doi_lp").count(),
            "pm": db.session.query(Url).filter(Url.url_type == "pm").count(),
            "pmc": db.session.query(Url).filter(Url.url_type == "pmc").count(),
            "unpaywall": db.session.query(Url)
            .filter(Url.url_type == "unpaywall")
            .count(),
            "ojs": db.session.query(Url).filter(Url.url_type == "ojs").count(),
        },
        "requests": {
            "num": db.session.query(Request).count(),
            "lp": db.session.query(Request)
            .filter(Request.request_type == "doi_lp")
            .count(),
            "ncbi": db.session.query(Request)
            .filter(Request.request_type == "ncbi")
            .count(),
            "unpaywall": db.session.query(Request)
            .filter(Request.request_type == "unpaywall")
            .count(),
        },
        "fbrequests": db.session.query(FBRequest).count(),
    }
    return render_template("stats.html", title="Statistics", data=data)


@blueprint.after_app_request
def after_request(response) -> Response:
    for query in get_debug_queries():
        if query.duration >= 0.5:
            current_app.logger.warning(
                "Slow query: %s\nParameters: %s\nDuration: %fs\nContext: %s\n"
                % (query.statement, query.parameters, query.duration, query.context)
            )
    return response

app/templates/api.html
{% extends "base.html" %}

{% block title %}{{ title }} - Facebook Hidden Engagement{% endblock %}

{% block head %}
{% endblock %}

{% block header %}
<h1 class="text-center">API Version 1.0</h1>
{% endblock %}

{% block content %}
<div class="content">
  <h2><code>/api/v1</code></h2>
  <p><a href="{{ url_for('api.homepage') }}" title="API Version 1.0">/api/v1</a></p>
  <p>API version 1.0</p>
  <h4><code>/api/v1/add_data</code></h4>
  <p><a href="{{ url_for('api.add_data') }}" title="API Version 1.0 add_data/ endpoint">/api/v1/add_data</a></p>
  <p>Add raw data to the app. Data must come in the format specified <a href="https://github.com/ScholCommLab/fhe-collector/wiki/Data" title="/add_data API endpoint specificiation">here</a></p>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

app/templates/base.html
<!doctype html>
<head>
	<title>{{ title }}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0, user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta name="HandheldFriendly" content="True">
	<meta name="MobileOptimized" content="320">
	<meta http-equiv="cleartype" content="on">
	<meta http-equiv="expires" content="0">
	<link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='img/favicon.png') }}">
	<!-- Bootstrap 4 mit jQuery und Popper.js-->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
	<!-- Google Font - Open Sans -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
	<!-- FontAwesome -->
	<script src="https://use.fontawesome.com/f69251051b.js"></script>
	<!-- load css -->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}" />
	{% block head %}
	{% endblock %}
</head>
<body>
	<header id="header-main" class="header container">
		{% block header %}
		{% endblock %}
	</header>

	<div class="site container">
		{% block content %}
		{% endblock %}
	</div>

	<footer class="footer container">
		{% block footer %}
		{% endblock %}
	</footer>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}{{ title }} - Facebook Hidden Engagement Collector{% endblock %}

{% block head %}
{% endblock %}

{% block header %}
<h1 class="text-center">Home</h1>
{% endblock %}

{% block content %}
<div class="">
  <ul>
    <li><a href="{{ url_for('api.index') }}" title="API">/api</a></li>
    <li><a href="{{ url_for('v1.index') }}" title="API">/api/v1</a></li>
    <li><a href="{{ url_for('main.stats') }}" title="Statistics">/stats</a></li>
  </ul>

</div>
{% endblock %}

{% block footer %}
{% endblock %}

app/templates/stats.html
{% extends "base.html" %}

{% block title %}{{ title }} - Facebook Hidden Engagement Collector{% endblock %}

{% block head %}
{% endblock %}

{% block header %}
<h1 class="text-center">Home</h1>
{% endblock %}

{% block content %}
<div class="">
  <table>
    <tr>
      <th>Tables/Data</th>
      <th>num</th>
      <th>doi new</th>
      <th>doi old</th>
      <th>doi lp</th>
      <th>ncbi</th>
      <th>pm</th>
      <th>pmc</th>
      <th>unpaywall</th>
    </tr>
    <tr>
      <td>Imports</td>
      <td>{{ data.imports }}</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>Dois (open)</td>
      <td>{{ data.dois.num }}</td>
      <td>{{ data.dois.new }}</td>
      <td>{{ data.dois.old }}</td>
      <td>{{ data.dois.lp }}</td>
      <td>{{ data.dois.ncbi }}</td>
      <td>{{ data.dois.pmc }}</td>
      <td>{{ data.dois.pmc }}</td>
      <td>{{ data.dois.unpaywall }}</td>
    </tr>
    <tr>
      <td>URLs</td>
      <td>{{ data.urls.num }}</td>
      <td>{{ data.urls.new }}</td>
      <td>{{ data.urls.old }}</td>
      <td>{{ data.urls.lp }}</td>
      <td></td>
      <td>{{ data.urls.pm }}</td>
      <td>{{ data.urls.pmc }}</td>
      <td>{{ data.urls.unpaywall }}</td>
    </tr>
    <tr>
      <td>Requests</td>
      <td>{{ data.requests.num }}</td>
      <td></td>
      <td></td>
      <td>{{ data.requests.lp }}</td>
      <td>{{ data.requests.ncbi }}</td>
      <td></td>
      <td></td>
      <td>{{ data.requests.unpaywall }}</td>
    </tr>
    <tr>
      <td>FB Requests</td>
      <td>{{ data.fbrequests }}</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </table>
  <button><a href="{{ url_for('main.index') }}" title="Home">Home</a></button>
</div>
{% endblock %}

{% block footer %}
{% endblock %}